export const metropolitanCities = [
    "Tokyo, Japan",
    "Delhi, India",
    "Shanghai, China",
    "São Paulo, Brazil",
    "Mexico City, Mexico",
    "Cairo, Egypt",
    "Dhaka, Bangladesh",
    "Mumbai, India",
    "Beijing, China",
    "Osaka, Japan",
    "New York, NY",
    "Karachi, Pakistan",
    "Chongqing, China",
    "Istanbul, Turkey",
    "Buenos Aires, Argentina",
    "Kolkata, India",
    "Kinshasa, Democratic Republic of the Congo",
    "Manila, Philippines",
    "Rio de Janeiro, Brazil",
    "Tianjin, China",
    "Guangzhou, China",
    "Lagos, Nigeria",
    "Rio de Janeiro, Brazil",
    "Moscow, Russia",
    "London, United Kingdom",
    "Chennai, India",
    "Lima, Peru",
    "Bangkok, Thailand",
    "Hyderabad, India",
    "Wuhan, China",
    "Hangzhou, China",
    "Chennai, India",
    "Paris, France",
    "Bogotá, Colombia",
    "Santiago, Chile",
    "Johannesburg, South Africa",
    "Lagos, Nigeria",
    "Los Angeles, USA",
    "Barcelona, Spain",
    "Berlin, Germany",
    "Madrid, Spain",
    "Toronto, Canada",
    "Melbourne, Australia",
    "Sydney, Australia",
    "Toronto, Canada",
    "Philadelphia, USA",
    "San Francisco, USA",
    "Seattle, USA",
    "Phoenix, USA",
    "Dallas, USA",
    "Miami, USA",
    "Atlanta, USA",
    "Washington D.C., USA",
    "Montreal, Canada",
    "Vancouver, Canada",
    "Kuala Lumpur, Malaysia",
    "Singapore",
    "Hanoi, Vietnam",
    "Ho Chi Minh City, Vietnam",
    "Taipei, Taiwan",
    "Ankara, Turkey",
    "Lisbon, Portugal",
    "Budapest, Hungary",
    "Prague, Czech Republic",
    "Vienna, Austria",
    "Brussels, Belgium",
    "Amsterdam, Netherlands",
    "Zurich, Switzerland",
    "Oslo, Norway",
    "Stockholm, Sweden",
    "Copenhagen, Denmark",
    "Helsinki, Finland",
    "Reykjavik, Iceland"
  ];
  